### PR TITLE
Setup processes before running

### LINKED ISSUE #103: rethink how nodes are initialized vs started
Right now initializing nodes is done during the same step than starting them. This leads to problems when trying to bring up complex topologies where we need to start nodes roughly at the same time (ie, within seconds of each other) to avoid triggering catchup.

Specifically, `local_process:setup` performs a few expensive operations, such as database initialization and history archive initialization.

That code is called by `process:run`:
```ruby
    def run
      raise Process::AlreadyRunning, "already running!" if running?
      raise Process::Crash, "process #{name} has crashed. cannot run process again" if crashed?

      setup ##### <<< This is the expensive call
      launch_process
      @launched = true

      wait_for_http 
      set_upgrades
    end
```

The solution is probably to decouple those two steps by:
* adding a new boolean field "initialized" (making `setup` noop if it was already run)
* changing `commander:start_all_processes` to first loop and initialize nodes before calling `p.run`
* there might be a need for forcing `setup` to do its work (or a way to clear the `initialized` bool), looking at how `process` is used, it doesn't seem to be the case though

### PR DESCRIPTION
**Pull request by jonjove**
Resolves #103

### CODE REVIEW

File: lib/stellar_core_commander/process.rb [hunk 1]
```diff
@@ -727,6 +728,14 @@ def run
       set_upgrades
     end
 
+    Contract None => Any
+    def setup
+      if not @is_setup
```
Comment (nullstyle) [inline lib/stellar_core_commander/process.rb]: Fun fact:  `unless` is also a conditional in ruby :)

**Comment by nullstyle** [comment]
LGTM!
